#!/usr/bin/python

#*****************************************************************************
#* duplicate-transform: A script that duplicates the transform headers
#*****************************************************************************
#* Copyright (C) 2014-2015 BBC
#*
#* Authors: James P. Weaver <james.barrett@bbc.co.uk>
#*
#* This program is free software; you can redistribute it and/or modify
#* it under the terms of the GNU General Public License as published by
#* the Free Software Foundation; either version 2 of the License, or
#* (at your option) any later version.
#*
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#* GNU General Public License for more details.
#*
#* You should have received a copy of the GNU General Public License
#* along with this program; if not, write to the Free Software
#* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02111, USA.
#*
#* This program is also available under a commercial proprietary license.
#* For more information, contact us at ipstudio@bbc.co.uk.
#*****************************************************************************

import sys
import re

infilename = sys.argv[1]
outfilename = sys.argv[2]

inext = sys.argv[3]
outext = sys.argv[4]

fi = open(infilename, 'r')
fo = open(outfilename, 'w')

for l in fi:
    l = re.sub(inext, outext, l)
    fo.write(l)
